[package]
name = "ralaire"
version.workspace = true
edition.workspace = true


[dependencies]
ralaire_core.workspace = true
ralaire_vello.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
winit.workspace = true
vello.workspace = true
parley.workspace = true
[workspace]
members = ["core", "vello"]

[workspace.package]
version = "0.1.0"
edition = "2021"


[workspace.dependencies]
ralaire = { version = "0.1", path = "." }
ralaire_core = { version = "0.1", path = "core" }
ralaire_vello = { version = "0.1", path = "vello" }
bitflags = "2.4.1"
tokio = { version = "1.35.1", features = ["full"] }
futures = "0.3.30"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
winit = { git = "https://github.com/rust-windowing/winit/", default-features = false, features = [
    "rwh_06",
    "wayland",

] }
vello = { git = "https://github.com/additional-pumpkin/vello.git" }
parley = { git = "https://github.com/dfrg/parley" }
peniko = { git = "https://github.com/linebender/peniko", rev = "629fc3325b016a8c98b1cd6204cb4ddf1c6b3daa" }
rayon = "1.8.0"
