[package]
name = "ralaire_core"
version.workspace = true
edition.workspace = true


[dependencies]
peniko.workspace = true
bitflags.workspace = true
winit.workspace = true
tracing.workspace = true
parley.workspace = true
